h.f1 = figure;
try
    set(h.f1, 'WindowState', 'maximized');
catch
    % for earlier version
    set(h.f1,'Position',get(0,'Screensize'));
end
h.panel0 = uipanel(gcf,'Position',[0 0.9 0.8 0.1],...
    'BorderWidth',0);
h.p0btn1 = uicontrol(h.panel0,'Style','pushbutton',...
    'String','Load Data',...
    'Position',[10,30,100,30],...
    'Callback','Load_Data');
h.p0status1 = uicontrol(h.panel0,'Style','text',...
    'String','Current data: ?',...
    'Position',h.p0btn1.Position+[100,0,800,0]);
% h.p0btn2 = uicontrol(h.panel0,'Style','pushbutton',...
%     'String','Save Screen',...
%     'Position',[10,0,100,30],...
%     'Callback','Save_Screen');%% Couldn't get it to work, also kind of
%     pointless
h.p0status2 = uicontrol(h.panel0,'Style','text',...
    'String','Load patient data to start',...
    'BackgroundColor',[0,0,0],...
    'ForegroundColor',[0,1,0],...
    'FontWeight','Bold',...
    'FontSize',10,...
    'Position',h.p0btn1.Position+[100,30,450,0]);

h.ax1 = axes('Position',[0.002,0.22,0.35,0.65]);
h.ax2 = axes('Position',[0.36,  0.22,0.35,0.65]);
h.ax1_2 = axes('Position',[0.002,0.22,0.35,0.65],'visible','off');
h.ax2_2 = axes('Position',[0.36,  0.22,0.35,0.65],'visible','off');

h.ax3 = axes('Position',[0.85,0.85,0.14,0.10]);
hold on;plot(1);plot(2);plot(3);
h.ax3.Children(1).XData = [];
h.ax3.Children(1).YData = [];
h.ax3.Children(2).XData = [];
h.ax3.Children(2).YData = [];
h.ax3.Children(3).XData = [];
h.ax3.Children(3).YData = [];
h.ax3.Children(3).Color = [0.2,0.2,1];
h.ax3.Children(2).Color = [1,0.2,0.2];
h.ax3.Children(1).Color = [0.2,1,0.2];
legend('Tumour','Blood','Extra Tissue');
xlabel('Time');
ylabel('Mean Intensity');

h.ax4 = axes('Position',[0.85,0.54,0.14,0.27]);
h.ax5 = axes('Position',[0.85,0.20,0.14,0.27]);

h.xoffset = [130,0,0,0];
h.yoffset = [0,30,0,0];
h.panel1 = uipanel(gcf,'Position',[0 0 0.45 0.18],...
    'BorderWidth',0);
h.p1slice1 = uicontrol(h.panel1,'Style','slider',...
    'Position',[10,140,120,20],...
    'Callback','drawslicedimage1');
h.p1text1 = uicontrol(h.panel1,'Style','text',...
    'String','Slice: ?',...
    'Position',h.p1slice1.Position+h.xoffset);
h.p1time1 = uicontrol(h.panel1,'Style','slider',...
    'Position',h.p1slice1.Position-h.yoffset,...
    'Callback','drawslicedimage1');
h.p1text2 = uicontrol(h.panel1,'Style','text',...
    'String','Time: ?',...
    'Position',h.p1time1.Position+h.xoffset);

h.panel2 = uipanel(gcf,'Position',[0.4 0 0.6 0.18],...
    'BorderWidth',0);
h.p2slice1 = uicontrol(h.panel2,'Style','slider',...
    'Position',[10,140,120,20],...
    'Callback','drawslicedimage2',...
    'Visible','off');  % Invisible slider for figure 2 as it is not useful
h.p2text1 = uicontrol(h.panel2,'Style','text',...
    'String','Slice: ?',...
    'Position',h.p2slice1.Position+h.xoffset,...
    'Visible','off');   % The text for slider for figure 2 is not useful.
h.p2time1 = uicontrol(h.panel2,'Style','slider',...
    'Position',h.p2slice1.Position-h.yoffset,...
    'Callback','drawslicedimage2');
h.p2text2 = uicontrol(h.panel2,'Style','text',...
    'String','Time: ?',...
    'Position',h.p2time1.Position+h.xoffset);
h.p2btn1 = uicontrol(h.panel2,'Style','pushbutton',...
    'Position',h.p2text1.Position+h.xoffset,...
    'String','Draw Tumour ROI',...
    'Callback','Draw_Tumour_ROI');
h.p2btn2 = uicontrol(h.panel2,'Style','pushbutton',...
    'Position',h.p2btn1.Position+h.xoffset,...
    'String','Draw Blood ROI',...
    'Callback','Draw_Blood_ROI');
h.p2btn3 = uicontrol(h.panel2,'Style','pushbutton',...
    'Position',h.p2btn2.Position+h.xoffset,...
    'String','Draw Extra ROI',...
    'Callback','Draw_Extra_ROI');
h.p2btn4 = uicontrol(h.panel2,'Style','pushbutton',...
    'Position',h.p2btn3.Position+h.xoffset,...
    'String','Update ROI',...
    'Callback','Update_Ref_of_ROI');
% h.p2btn5 = uicontrol(h.panel2,'Style','pushbutton',...
%     'Position',h.p2btn4.Position+h.xoffset+[0,0,0,20],...
%     'String','Corroef Seg',...
%     'Callback','Corroef_Seg');
h.p2btn6 = uicontrol(h.panel2,'Style','pushbutton',...
    'Position',h.p2btn4.Position+h.xoffset,...
    'String','Popup curve',...
    'Callback','Popup_curve');
h.p2btn7 = uicontrol(h.panel2,'Style','pushbutton',...
    'Position',h.p2btn6.Position+h.xoffset,...
    'String','Popup 3D',...
    'Callback','Popup_3D');

h.p2text10 = uicontrol(h.panel2,'Style','text',...
    'Position',h.p2time1.Position-h.yoffset-h.xoffset/5,...
    'String','Threshold');
pause(0.01);
h.p2edit10 = uicontrol(h.panel2,'Style','edit',...
    'Position',h.p2text10.Position+[90,0,-90,0],...
    'String',num2str(corr_threshold));
pause(0.01);
h.p2btn10 = uicontrol(h.panel2,'Style','pushbutton',...
    'Position',h.p2text10.Position-h.yoffset,...
    'String','Segmentation',...
    'Callback','Corroef_Seg');
h.p2btn11 = uicontrol(h.panel2,'Style','pushbutton',...
    'Position',h.p2btn10.Position+h.xoffset,...
    'String','DrawMU3D',...
    'Callback','DrawMU3D');
h.p2checkbox = uicontrol(h.panel2,'Style','checkbox',...
    'String','Show Extra tissue?',...
    'Position',h.p2btn11.Position+h.yoffset);
h.p2filter1 = uicontrol(h.panel2,'Style','slider',...
    'Position',h.p2btn11.Position+2*h.yoffset+h.xoffset,...
    'Min',1,...
    'Max',100,...
    'SliderStep',[1/100,0.2],...
    'Value',filter_size_Vtumour,...
    'Callback','FilterTumour');
h.p2filter2 = uicontrol(h.panel2,'Style','slider',...
    'Position',h.p2filter1.Position-h.yoffset,...
    'Min',1,...
    'Max',100,...
    'SliderStep',[1/100,0.2],...
    'Value',filter_size_Vblood,...
    'Callback','FilterBlood');    
h.p2filter3 = uicontrol(h.panel2,'Style','slider',...
    'Position',h.p2filter2.Position-h.yoffset,...
    'Min',1,...
    'Max',100,...
    'SliderStep',[1/100,0.2],...
    'Value',filter_size_Vmuscle,...
    'Callback','FilterMuscle');   
h.p2filter1text = uicontrol(h.panel2,'Style','text',...
    'String',['Tumour Filter: ',fix(num2str(h.p2filter1.Value))],...
    'Position',h.p2filter1.Position+h.xoffset);
h.p2filter2text = uicontrol(h.panel2,'Style','text',...
    'String',['Blood Filter: ',fix(num2str(h.p2filter2.Value))],...
    'Position',h.p2filter2.Position+h.xoffset);
h.p2filter3text = uicontrol(h.panel2,'Style','text',...
    'String',['Muscle Filter: ',fix(num2str(h.p2filter3.Value))],...
    'Position',h.p2filter3.Position+h.xoffset);


h.p2checkbox10 = uicontrol(h.panel2,'Style','checkbox',...
    'Position',h.p2filter3text.Position+h.xoffset,...
    'String','Single[Y] or Full[N] color',...
    'Callback','Single_or_Full_color');
h.p2slice3 = uicontrol(h.panel2,'Style','slider',...
    'Position',h.p2checkbox10.Position+h.yoffset);
h.p2text3 = uicontrol(h.panel2,'Style','text',...
    'String','slice: ?',...
    'Position',h.p2slice3.Position+h.xoffset);

pause(0.01);